import pg from 'pg';
const { Client } = pg;

const DB_PASSWORD = process.env.DB_PASSWORD || '';
const PROJECT_REF = process.env.PROJECT_REF || '';

const client = new Client({
  host: 'aws-0-ap-southeast-1.pooler.supabase.com',
  port: 6543,
  user: `postgres.${PROJECT_REF}`,
  password: DB_PASSWORD,
  database: 'postgres',
  ssl: { rejectUnauthorized: false },
});

const ALL_20_PROVIDERS = [
  {
    id: 'PRV_TELKOM',
    name: '1. TELKOM INDONESIA',
    code: 'TLKM',
    color: '#ef4444',
    status: 'ACTIVE',
  },
  {
    id: 'PRV_MNC_1',
    name: '2. MNC PLAY (Tipe A)',
    code: 'MNC',
    color: '#475569',
    status: 'ACTIVE',
  },
  { id: 'PRV_FIRSTMEDIA', name: '3. FIRST MEDIA', code: 'FM', color: '#16a34a', status: 'ACTIVE' },
  {
    id: 'PRV_MNC_2',
    name: '4. MNC PLAY (Tipe B)',
    code: 'MNC',
    color: '#475569',
    status: 'ACTIVE',
  },
  { id: 'PRV_BIZNET', name: '5. BIZNET NETWORKS', code: 'BIZ', color: '#f97316', status: 'ACTIVE' },
  {
    id: 'PRV_MORATEL_1',
    name: '6. MORATELINDO (Bawah Kuning)',
    code: 'MORA',
    color: '#eab308',
    status: 'ACTIVE',
  },
  { id: 'PRV_IFORTE', name: '7. IFORTE', code: 'IFORTE', color: '#3b82f6', status: 'ACTIVE' },
  {
    id: 'PRV_LINTASARTA',
    name: '8. LINTASARTA (LA)',
    code: 'LA',
    color: '#0ea5e9',
    status: 'ACTIVE',
  },
  {
    id: 'PRV_MSA',
    name: '9. MSA (Megasurya Angkasa)',
    code: 'MSA',
    color: '#38bdf8',
    status: 'ACTIVE',
  },
  { id: 'PRV_FIBERSTAR', name: '10. FIBERSTAR', code: 'FSTAR', color: '#06b6d4', status: 'ACTIVE' },
  {
    id: 'PRV_XL_1',
    name: '11. XL AXIATA (Biru Polos)',
    code: 'XL',
    color: '#2563eb',
    status: 'ACTIVE',
  },
  {
    id: 'PRV_INDOSAT',
    name: '12. INDOSAT OOREDOO',
    code: 'ISAT',
    color: '#eab308',
    status: 'ACTIVE',
  },
  {
    id: 'PRV_TBG',
    name: '13. TBG (Tower Bersama Group)',
    code: 'TBG',
    color: '#22c55e',
    status: 'ACTIVE',
  },
  {
    id: 'PRV_MORATEL_2',
    name: '14. MORATELINDO (Sabuk Kuning)',
    code: 'MORA',
    color: '#eab308',
    status: 'ACTIVE',
  },
  {
    id: 'PRV_SMARTFREN',
    name: '15. SMARTFREN TELECOM',
    code: 'SMART',
    color: '#ec4899',
    status: 'ACTIVE',
  },
  { id: 'PRV_CBN', name: '16. CBN FIBER', code: 'CBN', color: '#f97316', status: 'ACTIVE' },
  {
    id: 'PRV_BALITOWER',
    name: '17. BALI TOWERINDO',
    code: 'BALI',
    color: '#8b5cf6',
    status: 'ACTIVE',
  },
  {
    id: 'PRV_PLN_ICON',
    name: '18. PLN ICON PLUS (ICONNET)',
    code: 'ICON',
    color: '#0284c7',
    status: 'ACTIVE',
  },
  {
    id: 'PRV_XL_2',
    name: '19. XL HOME FIBER (Sabuk Kuning)',
    code: 'XL',
    color: '#2563eb',
    status: 'ACTIVE',
  },
  {
    id: 'PRV_MYREPUBLIC',
    name: '20. MYREPUBLIC INDONESIA',
    code: 'MYREP',
    color: '#9333ea',
    status: 'ACTIVE',
  },
];

const EXACT_SHEET_POLES = [
  {
    id: 'LL-0001',
    pole_code: 'LLG-T1-MAJ-418',
    pole_latitude: -3.277098,
    pole_longitude: 102.908949,
    device_latitude: null,
    device_longitude: null,
    gps_accuracy: null,
    distance_from_device: null,
    location_method: 'MANUAL_MAP_PIN',
    provider_id: 'PRV_TELKOM',
    provider_name: '1. TELKOM INDONESIA',
    pole_type: 'BESI',
    condition: 'GOOD',
    road: 'Jl. Area Kel. Majapahit',
    kelurahan: 'Majapahit',
    kecamatan: 'Lubuklinggau Timur I',
    kota: 'Kota Lubuklinggau',
    patokan_lokasi: null,
    sisi_jalan: 'KIRI',
    height: '7m',
    ownership_status: 'SENDIRI',
    is_tilted: false,
    is_messy_cable: false,
    is_low_cable: false,
    is_corroded: false,
    is_obstructing: false,
    is_hazardous: false,
    description: null,
    photo_file_id: '1jBLeIB8Qny9izMt9UhQ81kbQMZYPRwLr',
    photo_url: 'https://lh3.googleusercontent.com/d/1jBLeIB8Qny9izMt9UhQ81kbQMZYPRwLr=w1000',
    surveyor_id: 'USR-KOMINFO-ADMIN',
    surveyor_name: 'Admin DISKOMINFO (Admin Teknis & Jaringan)',
    survey_date: '2026-08-25',
    survey_time: '22:23',
    validation_status: 'SUBMITTED',
    created_at: '2026-08-25T15:19:43.030Z',
    updated_at: '2026-08-25T15:29:59.461Z',
    infrastructure_category: 'FO_WIFI',
    pju_lamp_type: 'TIDAK_ADA',
    has_kwh_meter: false,
    cable_installation_type: 'UDARA',
  },
  {
    id: 'LL-0002',
    pole_code: 'LLG-T1-MAJ-860',
    pole_latitude: -3.277337946,
    pole_longitude: 102.9089856,
    device_latitude: -3.27735901,
    device_longitude: 102.9093906,
    gps_accuracy: 14.0,
    distance_from_device: 45.02,
    location_method: 'MANUAL_MAP_PIN',
    provider_id: 'PRV_TELKOM',
    provider_name: '1. TELKOM INDONESIA',
    pole_type: 'BESI',
    condition: 'GOOD',
    road: 'Jl. Area Kel. Majapahit',
    kelurahan: 'Majapahit',
    kecamatan: 'Lubuklinggau Timur I',
    kota: 'Kota Lubuklinggau',
    patokan_lokasi: null,
    sisi_jalan: 'KIRI',
    height: '7m',
    ownership_status: 'SENDIRI',
    is_tilted: false,
    is_messy_cable: false,
    is_low_cable: false,
    is_corroded: false,
    is_obstructing: false,
    is_hazardous: false,
    description: null,
    photo_file_id: '1wlsob8eZIQLMY9xqZqwxHm2Au6Z0s-Rk',
    photo_url: 'https://lh3.googleusercontent.com/d/1wlsob8eZIQLMY9xqZqwxHm2Au6Z0s-Rk=w1000',
    surveyor_id: 'USR-KOMINFO-ADMIN',
    surveyor_name: 'Admin DISKOMINFO (Admin Teknis & Jaringan)',
    survey_date: '2026-08-25',
    survey_time: '20:03',
    validation_status: 'SUBMITTED',
    created_at: '2026-08-25T13:03:56.624Z',
    updated_at: '2026-08-25T15:23:47.973Z',
    infrastructure_category: 'FO_WIFI',
    pju_lamp_type: 'TIDAK_ADA',
    has_kwh_meter: false,
    cable_installation_type: 'UDARA',
  },
  {
    id: 'LL-0003',
    pole_code: 'LLG-T1-MAJ-557',
    pole_latitude: -3.277553064,
    pole_longitude: 102.9090288,
    device_latitude: -3.277349721,
    device_longitude: 102.9094207,
    gps_accuracy: 4.46,
    distance_from_device: 49.03,
    location_method: 'MANUAL_MAP_PIN',
    provider_id: 'PRV_TELKOM',
    provider_name: '1. TELKOM INDONESIA',
    pole_type: 'BESI',
    condition: 'GOOD',
    road: 'Jl. Area Kel. Majapahit',
    kelurahan: 'Majapahit',
    kecamatan: 'Lubuklinggau Timur I',
    kota: 'Kota Lubuklinggau',
    patokan_lokasi: null,
    sisi_jalan: 'KIRI',
    height: '7m',
    ownership_status: 'SENDIRI',
    is_tilted: false,
    is_messy_cable: false,
    is_low_cable: false,
    is_corroded: false,
    is_obstructing: false,
    is_hazardous: false,
    description: null,
    photo_file_id: null,
    photo_url: null,
    surveyor_id: 'USR-KOMINFO-ADMIN',
    surveyor_name: 'Admin DISKOMINFO (Admin Teknis & Jaringan)',
    survey_date: '2026-08-25',
    survey_time: '20:05',
    validation_status: 'SUBMITTED',
    created_at: '2026-08-25T13:05:25.273Z',
    updated_at: '2026-08-25T15:27:04.125Z',
    infrastructure_category: 'FO_WIFI',
    pju_lamp_type: 'TIDAK_ADA',
    has_kwh_meter: false,
    cable_installation_type: 'UDARA',
  },
  {
    id: 'LL-0004',
    pole_code: 'LLG-B1-PJ-668',
    pole_latitude: -3.326702376,
    pole_longitude: 102.8255814,
    device_latitude: -3.326755243,
    device_longitude: 102.8255241,
    gps_accuracy: 14.52,
    distance_from_device: 8.66,
    location_method: 'MANUAL_MAP_PIN',
    provider_id: 'PRV_TELKOM',
    provider_name: '1. TELKOM INDONESIA',
    pole_type: 'BETON',
    condition: 'GOOD',
    road: 'Jalan Garuda',
    kelurahan: 'Pelita Jaya',
    kecamatan: 'Lubuklinggau Barat I',
    kota: 'Kota Lubuklinggau',
    patokan_lokasi: null,
    sisi_jalan: 'TIDAK_DITENTUKAN',
    height: '7m',
    ownership_status: 'SENDIRI',
    is_tilted: false,
    is_messy_cable: false,
    is_low_cable: false,
    is_corroded: false,
    is_obstructing: false,
    is_hazardous: false,
    description: null,
    photo_file_id: null,
    photo_url: null,
    surveyor_id: 'USR-SURVEYOR-02',
    surveyor_name: 'Yodi Heropralaga (Petugas Survei Spasial & Pemetaan)',
    survey_date: '2026-08-27',
    survey_time: '12:27',
    validation_status: 'SUBMITTED',
    created_at: '2026-08-27T05:28:09.298Z',
    updated_at: '2026-08-27T05:28:09.298Z',
    infrastructure_category: 'FO_WIFI',
    pju_lamp_type: 'TIDAK_ADA',
    has_kwh_meter: false,
    cable_installation_type: 'UDARA',
  },
  {
    id: 'LL-0005',
    pole_code: 'LLG-B1-PJ-668',
    pole_latitude: -3.326702376,
    pole_longitude: 102.8255814,
    device_latitude: -3.326755243,
    device_longitude: 102.8255241,
    gps_accuracy: 14.52,
    distance_from_device: 8.66,
    location_method: 'MANUAL_MAP_PIN',
    provider_id: 'PRV_TELKOM',
    provider_name: '1. TELKOM INDONESIA',
    pole_type: 'BETON',
    condition: 'GOOD',
    road: 'Jalan Garuda',
    kelurahan: 'Pelita Jaya',
    kecamatan: 'Lubuklinggau Barat I',
    kota: 'Kota Lubuklinggau',
    patokan_lokasi: null,
    sisi_jalan: 'TIDAK_DITENTUKAN',
    height: '7m',
    ownership_status: 'SENDIRI',
    is_tilted: false,
    is_messy_cable: false,
    is_low_cable: false,
    is_corroded: false,
    is_obstructing: false,
    is_hazardous: false,
    description: null,
    photo_file_id: null,
    photo_url: null,
    surveyor_id: 'USR-SURVEYOR-02',
    surveyor_name: 'Yodi Heropralaga (Petugas Survei Spasial & Pemetaan)',
    survey_date: '2026-08-27',
    survey_time: '12:27',
    validation_status: 'SUBMITTED',
    created_at: '2026-08-27T05:29:25.691Z',
    updated_at: '2026-08-27T05:29:25.691Z',
    infrastructure_category: 'FO_WIFI',
    pju_lamp_type: 'TIDAK_ADA',
    has_kwh_meter: false,
    cable_installation_type: 'UDARA',
  },
  {
    id: 'LL-0006',
    pole_code: 'LLG-B1-PJ-530',
    pole_latitude: -3.326446656,
    pole_longitude: 102.8253472,
    device_latitude: -3.326423616,
    device_longitude: 102.8253441,
    gps_accuracy: 6.16,
    distance_from_device: 2.58,
    location_method: 'MANUAL_MAP_PIN',
    provider_id: 'PRV_TELKOM',
    provider_name: '1. TELKOM INDONESIA',
    pole_type: 'BESI',
    condition: 'GOOD',
    road: 'Jalan Garuda',
    kelurahan: 'Pelita Jaya',
    kecamatan: 'Lubuklinggau Barat I',
    kota: 'Kota Lubuklinggau',
    patokan_lokasi: 'Belakang bapenda',
    sisi_jalan: 'TIDAK_DITENTUKAN',
    height: '7m',
    ownership_status: 'SENDIRI',
    is_tilted: false,
    is_messy_cable: false,
    is_low_cable: false,
    is_corroded: false,
    is_obstructing: false,
    is_hazardous: false,
    description: null,
    photo_file_id: '1k-Nee2QBAeOZ66Zq6Wh0HpxfXyYzhTzP',
    photo_url: 'https://lh3.googleusercontent.com/d/1k-Nee2QBAeOZ66Zq6Wh0HpxfXyYzhTzP=w1000',
    surveyor_id: 'USR-SURVEYOR-04',
    surveyor_name: 'Pradigga Navigasi (Petugas Survei Spasial & Pemetaan)',
    survey_date: '2026-08-27',
    survey_time: '12:31',
    validation_status: 'SUBMITTED',
    created_at: '2026-08-27T05:33:13.610Z',
    updated_at: '2026-08-27T05:33:13.610Z',
    infrastructure_category: 'FO_WIFI',
    pju_lamp_type: 'TIDAK_ADA',
    has_kwh_meter: false,
    cable_installation_type: 'UDARA',
  },
];

async function runExactMigration() {
  console.log('================================================================');
  console.log(' 🚀 MENYINKRONKAN 100% STRUKTUR LENGKAP GOOGLE SHEETS KE SUPABASE');
  console.log('================================================================\n');

  await client.connect();
  console.log('✅ Terhubung ke Supabase PostgreSQL!');

  // 1. Buat Tabel Providers
  console.log('🏢 [1/3] Membuat tabel providers & menyuntikkan 20 Provider...');
  await client.query(`
    CREATE TABLE IF NOT EXISTS public.providers (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        code TEXT NOT NULL,
        color TEXT NOT NULL,
        status TEXT DEFAULT 'ACTIVE'
    );
    ALTER TABLE public.providers ENABLE ROW LEVEL SECURITY;
    DO $$ BEGIN
      DROP POLICY IF EXISTS "Allow public read on providers" ON public.providers;
      CREATE POLICY "Allow public read on providers" ON public.providers FOR SELECT USING (true);
    END $$;
  `);

  for (const prv of ALL_20_PROVIDERS) {
    await client.query(
      `
      INSERT INTO public.providers (id, name, code, color, status)
      VALUES ($1, $2, $3, $4, $5)
      ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        code = EXCLUDED.code,
        color = EXCLUDED.color,
        status = EXCLUDED.status;
    `,
      [prv.id, prv.name, prv.code, prv.color, prv.status]
    );
  }
  console.log(
    `✅ Sebanyak ${ALL_20_PROVIDERS.length} Provider Resmi berhasil tersimpan di Supabase!\n`
  );

  // 2. Suntikkan 6 Tiang dengan Akurasi Presisi
  console.log('📍 [2/3] Menyuntikkan 6 Data Tiang Riil Presisi Lengkap...');
  for (const p of EXACT_SHEET_POLES) {
    await client.query(
      `
      INSERT INTO public.poles (
        id, pole_code, pole_latitude, pole_longitude, device_latitude, device_longitude,
        gps_accuracy, distance_from_device, location_method, provider_id, provider_name,
        pole_type, condition, road, kelurahan, kecamatan, kota, patokan_lokasi, sisi_jalan,
        height, ownership_status, cable_installation_type, infrastructure_category,
        pju_lamp_type, has_kwh_meter, is_tilted, is_messy_cable, is_low_cable,
        is_hazardous, is_corroded, is_obstructing, description, photo_file_id, photo_url,
        surveyor_id, surveyor_name, survey_date, survey_time, validation_status,
        created_at, updated_at
      ) VALUES (
        $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19,
        $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34, $35, $36, $37, $38, $39,
        $40, $41
      )
      ON CONFLICT (id) DO UPDATE SET
        pole_code = EXCLUDED.pole_code,
        pole_latitude = EXCLUDED.pole_latitude,
        pole_longitude = EXCLUDED.pole_longitude,
        device_latitude = EXCLUDED.device_latitude,
        device_longitude = EXCLUDED.device_longitude,
        gps_accuracy = EXCLUDED.gps_accuracy,
        distance_from_device = EXCLUDED.distance_from_device,
        provider_id = EXCLUDED.provider_id,
        provider_name = EXCLUDED.provider_name,
        pole_type = EXCLUDED.pole_type,
        condition = EXCLUDED.condition,
        road = EXCLUDED.road,
        kelurahan = EXCLUDED.kelurahan,
        kecamatan = EXCLUDED.kecamatan,
        patokan_lokasi = EXCLUDED.patokan_lokasi,
        sisi_jalan = EXCLUDED.sisi_jalan,
        photo_file_id = EXCLUDED.photo_file_id,
        photo_url = EXCLUDED.photo_url,
        surveyor_id = EXCLUDED.surveyor_id,
        surveyor_name = EXCLUDED.surveyor_name,
        updated_at = EXCLUDED.updated_at;
    `,
      [
        p.id,
        p.pole_code,
        p.pole_latitude,
        p.pole_longitude,
        p.device_latitude,
        p.device_longitude,
        p.gps_accuracy,
        p.distance_from_device,
        p.location_method,
        p.provider_id,
        p.provider_name,
        p.pole_type,
        p.condition,
        p.road,
        p.kelurahan,
        p.kecamatan,
        p.kota,
        p.patokan_lokasi,
        p.sisi_jalan,
        p.height,
        p.ownership_status,
        p.cable_installation_type,
        p.infrastructure_category,
        p.pju_lamp_type,
        p.has_kwh_meter,
        p.is_tilted,
        p.is_messy_cable,
        p.is_low_cable,
        p.is_hazardous,
        p.is_corroded,
        p.is_obstructing,
        p.description,
        p.photo_file_id,
        p.photo_url,
        p.surveyor_id,
        p.surveyor_name,
        p.survey_date,
        p.survey_time,
        p.validation_status,
        p.created_at,
        p.updated_at,
      ]
    );
  }
  console.log(
    `✅ Sebanyak ${EXACT_SHEET_POLES.length} Tiang Lapangan Presisi berhasil tersimpan!\n`
  );

  await client.end();
  console.log('================================================================');
  console.log(' 🎉 SELURUH STRUKTUR & DATA GOOGLE SHEETS 100% MASUK SUPABASE!');
  console.log('================================================================');
}

runExactMigration().catch((e) => {
  console.error('Fatal error:', e);
  process.exit(1);
});
